Authentication options doc: wrap `on` in quotes
Trying to execute `tctl create -f cap.yml` without those quotes results in the following error:

```
ERROR: types.AuthPreferenceV2.Spec: types.AuthPreferenceSpecV2.SecondFactor: ReadString: expects " or n, but found t, error found in #10 byte of ...|_factor":true,"type"|..., bigger context ...|luster-auth-preference"},"spec":{"second_factor":true,"type":"local","webauthn":{"rp_id":"example.te|...
```

After adding the quotes the command goes through. I suppose it's because `on` evaluates to `true` in Yaml, but our code expects to be an `"on"` string.